// app/test/[slug]/page.tsx
import TestClient from "./TestClient";

type PageProps = {
  params: Promise<{ slug: string }>;
  searchParams: Promise<Record<string, string | undefined>>;
};

export default async function Page({ params, searchParams }: PageProps) {
  const { slug } = await params;
  const sp = await searchParams;

  // If the link was generated by admin "Create Link", sid will be present.
  // If someone opens /test/[slug] directly, sid will be empty and TestClient
  // will auto-start a submission.
  const initialSid = sp?.sid;

  const prefill = {
    // optional prefill if you send them in the URL
    first: sp?.first,
    last: sp?.last,
    name: sp?.name, // if you still pass "name", we split it in the client
    email: sp?.email,
    phone: sp?.phone,
  };

  return <TestClient slug={slug} initialSid={initialSid} prefill={prefill} />;
}
